/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    NavBar: typeof import('./../src/components/NavBar.vue')['default']
    'NavBar copy': typeof import('./../src/components/NavBar copy.vue')['default']
    Tabs: typeof import('./../src/components/Tabs.vue')['default']
    WaterfallsFlow: typeof import('./../src/components/WaterfallsFlow.vue')['default']
  }
}
