/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./../src/components/NavBar copy.vue')['default']
    NavBar: typeof import('./../src/components/NavBar.vue')['default']
    'NavBar copy': typeof import('./../src/components/NavBar copy.vue')['default']
    NutAddress: typeof import('nutui-uniapp/components/address/address.vue')['default']
    NutCodeInput: typeof import('nutui-uniapp/components/codeinput/codeinput.vue')['default']
    NutInput: typeof import('nutui-uniapp/components/input/input.vue')['default']
    NutInputNumber: typeof import('nutui-uniapp/components/inputnumber/inputnumber.vue')['default']
    NutPopup: typeof import('nutui-uniapp/components/popup/popup.vue')['default']
    NutSearchbar: typeof import('nutui-uniapp/components/searchbar/searchbar.vue')['default']
    NutSwiper: typeof import('nutui-uniapp/components/swiper/swiper.vue')['default']
    NutSwiperItem: typeof import('nutui-uniapp/components/swiperitem/swiperitem.vue')['default']
    NutSwitch: typeof import('nutui-uniapp/components/switch/switch.vue')['default']
    NutTabbar: typeof import('nutui-uniapp/components/tabbar/tabbar.vue')['default']
    NutTabbarItem: typeof import('nutui-uniapp/components/tabbaritem/tabbaritem.vue')['default']
    NutToast: typeof import('nutui-uniapp/components/toast/toast.vue')['default']
    Tabs: typeof import('./../src/components/Tabs.vue')['default']
    WaterfallsFlow: typeof import('./../src/components/WaterfallsFlow.vue')['default']
  }
}
