/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/home/home" |
       "/pages/message/message" |
       "/pages/my/coupon" |
       "/pages/my/edit-phone-change" |
       "/pages/my/edit-phone-code" |
       "/pages/my/edit-phone-start" |
       "/pages/my/edit-user" |
       "/pages/my/my" |
       "/pages/my-tool/address-add" |
       "/pages/my-tool/address-list" |
       "/pages/my-tool/distribution" |
       "/pages/shopping-cart/shopping-cart";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/home/home" | "/pages/message/message" | "/pages/shopping-cart/shopping-cart" | "/pages/my/my"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
