/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/home/home" |
       "/pages/home/direct-selling" |
       "/pages/home/group-buy" |
       "/pages/home/new-product" |
       "/pages/home/search" |
       "/pages/home/second-hand" |
       "/pages/home/shop-home" |
       "/pages/login/login" |
       "/pages/login/signin" |
       "/pages/message/chat" |
       "/pages/message/message" |
       "/pages/my/coupon" |
       "/pages/my/edit-phone-change" |
       "/pages/my/edit-phone-code" |
       "/pages/my/edit-phone-start" |
       "/pages/my/edit-user" |
       "/pages/my/merchant-enter" |
       "/pages/my/my" |
       "/pages/my/point-exchange" |
       "/pages/my/vip-center" |
       "/pages/my-tool/address-add" |
       "/pages/my-tool/address-list" |
       "/pages/my-tool/distribution" |
       "/pages/my-tool/feedback" |
       "/pages/my-tool/invite" |
       "/pages/my-tool/settings" |
       "/pages/my-tool/withdraw" |
       "/pages/order/order-list" |
       "/pages/product/comment" |
       "/pages/product/details" |
       "/pages/product/point-details" |
       "/pages/product/point-place-order" |
       "/pages/product/swiper" |
       "/pages/shopping-cart/shopping-cart" |
       "/pages/underwear/underwear-home" |
       "/pages/underwear/underwear-hot" |
       "/pages/underwear/underwear-major" |
       "/pages/underwear/underwear-story" |
       "/pages/underwear/underwear-tide";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/home/home" | "/pages/message/message" | "/pages/shopping-cart/shopping-cart" | "/pages/my/my"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
